### ISSUE TITLE
How to pass a custom lib directory so that it's recognized by `conf-gmp-paths`?

### ISSUE THREAD

**Issue by denismerigoux** [nberth/ez-conf-lib#4]
Hello @nberth, first of all thanks for your work on those config scripts to smoothen out the dependency search for GMP when there's an opam package relying on it :)

It turns out that your work is very important since it happens to power, through the `mlgmpidl` package, the generation of static binaries for the Mlang compiler (https://github.com/MLanguage/mlang/blob/master/mlang.opam#L27) used to produce the C code that levies the French income tax. Indeed, we want a compiler binary that runs free of any dynamic library dependency to be used in exotic mainframe environments, which is why we build GMP and MPFR ourselves with `musl-gcc` : https://github.com/MLanguage/mlang/blob/724393abfa5854c96be9acd82c938c1565edb5c2/.github/workflows/binary-releases.yml#L104-L107.

As of recent changes in the dependencies of  `mlgmpidl` (related to #1 I think), this custom build of GMP used by `mlgmpidl` is not recognized any more by the `conf-gmp-paths` opam package and our pipeline fails : https://github.com/MLanguage/mlang/actions/runs/8203899486/job/22443015122#step:5:4685.  We used to pass `MPFR_PREFIX=/tmp/gmp-prefix GMP_PREFIX=/tmp/gmp-prefix` to our `opam install . --deps-only` command but it looks like this way of communicating the custom lib directory of GMP and MPFR is not the way to do anymore.

Do you happen to know the way to communicate to `conf-gmp-paths`, in a Linux environment, a custom lib directory for GMP and/or MPFR ?

Thank you very much for your help !

**Comment by nberth** [comment]
Ah indeed, I had forgotten about this use case. Per-library customization is still missing in `ez-conf-lib`, which is supposed to be a generic script. Until I re-implement a way to deal with such a customization, `CPPFLAGS=-I/tmp/gmp-prefix/include LDFLAGS=-L/tmp/gmp-prefix/lib opam install . --deps-only` might do it. Please tell me if that's not the case.

**Comment by denismerigoux** [comment]
We'll see if that works :) https://github.com/MLanguage/mlang/actions/runs/8285037831/job/22671890192

**Comment by denismerigoux** [comment]
Thanks Nicolas, your solution seems to do something but then I have later problems when building the ocaml binary : https://github.com/MLanguage/mlang/actions/runs/8285037831/job/22671890192#step:6:58. I'll just disable the static build for now...
